### ISSUE TITLE
Daedalus Turbo

### ISSUE THREAD

**Issue by Awzaw** [sierkov/voting-agents#1]
Congratulations on Fund 9... Maybe you could join in on Twitter and present your point of view?

https://twitter.com/IOHK_Charles/status/1574863016712994816?t=pJLrqccfZKIEL3nTzsEApA&s=19

https://twitter.com/Fabian_vBergen/status/1574824530450812931?t=pJLrqccfZKIEL3nTzsEApA&s=19

**Comment by sierkov** [comment]
Thanks for bringing this up; responded in those threads.
Since this is related to a different project, it's better to use Ideascale's page: https://cardano.ideascale.com/c/idea/414953/

P.S. Closing this issue since it's unrelated to Voting Agents.
